services:
  mariadb:
    image: mariadb:lts
    container_name: mariadb_container
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db

  # 2. Das Web-Interface (Optional, aber hilfreich für Entwicklung)
  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_container
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongodb